FROM python:3.7.0-stretch

RUN apt-get update

WORKDIR /usr/src/app

COPY ./app/requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./app .

EXPOSE 8000

CMD [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]
