version: '3'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/python/Dockerfile
        restart: always
        ports:
            - '8000:8000'
        depends_on:
            - postgres
        volumes:
            - './app:/usr/src/app'
    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        restart: always
        env_file:
            - './docker/postgres/postgres.env'
        ports:
            - '5432:5432'
        volumes:
            - './docker/postgres/pgdata:/var/lib/postgresql/data'
